p2.catch( () => {
//     console.log("Some error o");
    
// } )